Benchmarks: micro benchmarks - add nvbandwidth build
microsoft/superbenchmark pull request #665
Opened 2024-11-16 08:24 UTC by polarG

**Description**
Add nvbandwidth build to repo

2024-11-18 00:10 UTC, abuccts approved these changes

2024-11-19 00:11 UTC, yzygitzh commented on third_party/Makefile
> +        echo "Skip nvbandwidth for CMake is not installed."; \
I think we should expose thrid-party dependency issues in this file instead of skipping it. Maybe we don't need to check cmake version here.

2024-11-19 00:12 UTC, yzygitzh requested changes

2024-11-19 00:12 UTC, yzygitzh commented on third_party/Makefile
> +        echo "Skip nvbandwidth for CMake is not installed."; \
I think we should expose thrid-party dependency issues in this file instead of skipping it. Maybe we don't need to check cmake version here.

2024-11-19 00:45 UTC, yzygitzh commented on third_party/Makefile
> +        echo "Skip nvbandwidth for CMake is not installed."; \
Discussed with @abuccts offline. Seems nvbandwidth will only be enabled for h100 and above nv gpus. In that case, can we change this to only enabled when this target is explicitly enabled when calling make? https://github.com/microsoft/superbenchmark/blob/main/third_party/Makefile#L23 and https://github.com/microsoft/superbenchmark/blob/main/dockerfile/cuda12.2.dockerfile#L142 can be a good reference.

2024-11-21 03:25 UTC, yzygitzh approved these changes

2024-11-21 12:01 UTC, merged